name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "admin-portal/**"
      - "backend/**"
      - ".github/workflows/**"

# Cancel previous runs for the same PR when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # ---------------- DETECT CHANGES ----------------
  detect-changes:
    name: Detect Changed Folders
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      # admin-portal: ${{ steps.filter.outputs.admin-portal }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  # ---------------- LINT: FRONTEND ----------------
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Run Linter
        run: pnpm run lint
        working-directory: ./frontend

  # ---------------- LINT: ADMIN PORTAL ----------------
  # lint-admin:
  #   name: Lint Admin Portal
  #   runs-on: ubuntu-latest
  #   needs: detect-changes
  #   if: needs.detect-changes.outputs.admin-portal == 'true'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: setup pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - name: Install dependencies
  #       run: pnpm install
  #       working-directory: ./admin-portal

  #     - name: Run Linter
  #       run: pnpm run lint
  #       working-directory: ./admin-portal

  # ---------------- LINT: BACKEND ----------------
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: ./backend

      - name: Run Linter
        run: pnpm run lint
        working-directory: ./backend

  # ---------------- FRONTEND BUILD ----------------
  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [detect-changes, lint-frontend]
    if: needs.detect-changes.outputs.frontend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Build project
        run: pnpm run build
        working-directory: ./frontend

      - name: Verify build output
        run: |
          if [ -f "frontend/dist/index.html" ]; then
              echo "✅ Build output valid."
          else
              echo "❌ Build output missing!"
              exit 1
          fi

  # ---------------- ADMIN BUILD ----------------
  # admin-build:
  #   name: Build Admin Portal
  #   runs-on: ubuntu-latest
  #   needs: [detect-changes, lint-admin]
  #   if: needs.detect-changes.outputs.admin-portal == 'true'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: setup pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - name: Install dependencies
  #       run: pnpm install
  #       working-directory: ./admin-portal

  #     - name: Build project
  #       run: pnpm run build
  #       working-directory: ./admin-portal

  #     - name: Verify build output
  #       run: |
  #         if [ -f "admin-portal/build/index.html" ]; then
  #             echo "✅ Build output valid."
  #         else
  #             echo "❌ Build output missing!"
  #             exit 1
  #         fi

  # ---------------- BACKEND TEST ----------------
  # backend-check:
  #   name: Test Backend
  #   runs-on: ubuntu-latest
  #   needs: [detect-changes, lint-backend]
  #   if: needs.detect-changes.outputs.backend == 'true'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: setup pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - name: Install dependencies
  #       run: pnpm install
  #       working-directory: ./backend

  #     - name: Run Tests
  #       run: pnpm test
  #       working-directory: ./backend
